# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Images and Publish Artifacts
  jobs:
  - job:
    displayName: 'Publish Artifacts'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Votingappimages'
        repository: 'worker-im'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/worker/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/worker'
    - task: Docker@2
      inputs:
        containerRegistry: 'Votingappimages'
        repository: 'result-im'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/result/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/result'
    - task: Docker@2
      inputs:
        containerRegistry: 'Votingappimages'
        repository: 'vote-im'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/vote/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/vote'
        addPipelineData: false
        addBaseImageData: false
    
    
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.yml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy to K8s
  jobs:  
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        itemPattern: '**/*.yml'
        targetPath: '$(System.ArtifactsDirectory)'     
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'K8s-cluster-connection'
        namespace: 'default'
        manifests: '$(System.ArtifactsDirectory)/deployment-acr.yml'
        containers: |
          'votingappimages.azurecr.io/result-im:$(tag)'
          'votingappimages.azurecr.io/worker-im:$(tag)'
          'votingappimages.azurecr.io/vote-im:$(tag)'
          'postgres:latest'
          'redis:5.0-alpine3.10'
        imagePullSecrets: 'regcred'
