# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  jobs:
  - job:
    displayName: 'Publish Artifacts'
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.yml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy image
  jobs:  
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        itemPattern: '**/*.yml'
        targetPath: '$(System.ArtifactsDirectory)'   
    - task: KubernetesManifest@0
      inputs:
        action: 'createSecret'
        kubernetesServiceConnection: 'K8scluster-connection'
        namespace: 'default'
        secretType: 'dockerRegistry'
        secretName: 'imgpullscrt'
        dockerRegistryEndpoint: 'Votingappimages'
          
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'K8scluster-connection'
        namespace: 'default'
        manifests: '$(System.ArtifactsDirectory)/deployment-acr.yml'
        imagePullSecrets: 'imgpullscrt'
        containers: |
          'votingappimages.azurecr.io/result-im:32'
          'votingappimages.azurecr.io/worker-im:32'
          'votingappimages.azurecr.io/vote-im:32'
          'postgres:latest'
          'redis:5.0-alpine3.10'
